### ISSUE TITLE
Draw a hardwareshop icon

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/graphics#26]
# Description of the new design
Draw an app-Icon for the hardware shop

# Problem
We don`t have an hardware shop icon

# Additional context
SVG-format, ViexBox 128x128px

# Steps

- [x] Check the new idea
- [ ] Create a new design
- [ ] Check the new design or animation in frontend
- [ ] Rework the design or animation if necessary
- [ ] Check again
- [ ] Finish the design (graphics as svg file)

**Comment by Chaozz66** [comment]
done and uploaded
