### ISSUE TITLE
Create a thumbnail for pre-alpha 1 release

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/graphics#31]
# Description of the new design
Create a thumbnail for pre-alpha 1 release video

# Steps

- [x] Check the new idea
- [x] Create a new design
- [x] Check the new design or animation in frontend
- [x] Rework the design or animation if necessary
- [x] Check again
- [x] Finish the design (graphics as svg file)

**Comment by Nocuma** [comment]
![Pre-Alpha 1 Release](https://user-images.githubusercontent.com/50842114/83356942-9f6f8180-a369-11ea-9ea8-36900201ead8.png)

**Comment by DevMimas** [comment]
Schreib Released mit "d" am Ende.
Release = Veröffentlichung
Released = Veröffentlicht

**Comment by DevMimas** [comment]
done
