### ISSUE TITLE
Create a thumbnail for pre-alpha 2 update

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/graphics#32]
# Description of the new design
Create a thumbnail for pre-alpha 2 update video

# Steps

- [x] Check the new idea
- [x] Create a new design
- [x] Check the new design or animation in frontend
- [x] Rework the design or animation if necessary
- [x] Check again
- [x] Finish the design (graphics as svg file)

**Comment by Nocuma** [comment]
![Pre-Alpha 2 Update](https://user-images.githubusercontent.com/50842114/83356932-9383bf80-a369-11ea-936d-61c9e1cb0e1b.png)

**Comment by DevMimas** [comment]
Joa. Sieht schon schick aus. Nur das Hintergrundbild sieht mehr aus wie ne Stadt, ganz weit rausgezoomt. So wirklich erkennt man das nicht als Mainboard oder so. Glaube da sollten der Hintergrund von der Struktur grober sein.

**Comment by DevMimas** [comment]
done
