### ISSUE TITLE
Draw an controlcenter icon

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/graphics#34]
# Description of the new design
Draw a control centre Icon

# Problem
We don`t have a control centre icon

# Additional context
SVG-format, ViexBox 128x128px

# Steps

- [x] Check the new idea
- [ ] Create a new design
- [ ] Check the new design or animation in frontend
- [ ] Rework the design or animation if necessary
- [ ] Check again
- [ ] Finish the design (graphics as svg file)

**Comment by Chaozz66** [comment]
done
